drm/msm: dp: Fixup queue_work for realme changes
../drivers/gpu/drm/msm/dp/dp_display.c:679:22: error: incompatible pointer types passing 'struct delayed_work *' to parameter of type 'struct work_struct *' [-Werror,-Wincompatible-pointer-types]
                queue_work(dp->wq, &dp->connect_work);
                                   ^~~~~~~~~~~~~~~~~
../include/linux/workqueue.h:489:30: note: passing argument to parameter 'work' here
                              struct work_struct *work)
                                                  ^
1 error generated.

Caused by e7ec1d0c4dd35a4ae07961cd61ba49ba51ce536a (11500 merge)